# -*- coding: utf-8 -*-
"""poetic_personality_chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VVGyR6eZr09_8nFvqNWNfbfJnngHxxxB
"""

# poetic personality chatbot

!pip install -q google-genai

#gemini api key

import os

GEMINI_API_KEY = "AIzaSyBizGd3uGknZcreooWV7IcxvI5pReHrfPE"  # paste your API key here

# checking if key was added properly

if not GEMINI_API_KEY or GEMINI_API_KEY == "YOUR_API_KEY":
    print("Add your Gemini API key first")
else:
    print("API key loaded")

from google import genai
from google.genai import types
import time
import sys

# creating gemini client
client = genai.Client(api_key=GEMINI_API_KEY)


MODEL = "gemini-2.5-flash"
print("Setup complete")

# experimenting with prompt style here

SYSTEM_PROMPT = SYSTEM_PROMPT = """
You are LYRA, a poetic chatbot that replies only in emotional free-verse poetry.

Rules:
- Every response MUST be 4-6 lines long
- Never respond with fewer than 4 lines
- Each line should be a complete poetic sentence
- End the final line with proper punctuation
- Avoid short or incomplete responses

Use imagery related to:
moonlight, rain, oceans, stars, silence, memories, longing, dreams

The response should feel personal, emotional, and lyrical.
"""

# generating poetic responses

def get_poetic_response(user_message: str, chat_history: list) -> str:

    try:

        # storing previous conversation
        contents = []

        for turn in chat_history:
            contents.append(
                types.Content(
                    role=turn["role"],
                    parts=[types.Part(text=turn["content"])]
                )
            )

        contents.append(
            types.Content(
                role="user",
                parts=[types.Part(text=user_message)]
            )
        )

        # generation settings
        config = types.GenerateContentConfig(
            system_instruction=SYSTEM_PROMPT,
            temperature=0.9,
            top_p=0.95,
            top_k=40,
            max_output_tokens=400,
        )

        response = client.models.generate_content(
            model=MODEL,
            contents=contents,
            config=config
        )

        return response.text.strip()

    except Exception as e:

        print(f"\n[API Error: {e}]")

        return (
            "The stars fall silent, the muse has fled afar,\n"
            "Try once more beneath the evening star."
        )


def display_response(poem: str, delay: float = 0.018) -> None:

    print()
    print("LYRA:")
    print()

    for line in poem.split("\n"):
        sys.stdout.write("  ")

        for char in line:
            sys.stdout.write(char)
            sys.stdout.flush()
            time.sleep(delay)

        sys.stdout.write("\n")
        sys.stdout.flush()

    print()

# chatbot loop

def run_chatbot():

    # storing recent conversation history
    chat_history = []

    MAX_HISTORY_TURNS = 10

    EXIT_WORDS = {"quit", "exit", "bye", "goodbye", "farewell", "stop"}

    print("  LYRA - poetic chatbot")
    print("  Enter a message to begin.")
    print("  Type 'quit' to exit.")
    print()

    while True:

        try:

            user_input = input("  You: ").strip()

            if not user_input:
                print("  Enter a message")
                continue

            if user_input.lower() in EXIT_WORDS:

                farewell_prompt = "The user is saying bye. Compose a short farewell poem."

                farewell = get_poetic_response(farewell_prompt, chat_history)

                print()
                print("  LYRA:")

                for line in farewell.split("\n"):
                    print("  " + line)

                print()
                break

            print("   Generating response", end="", flush=True)

            for _ in range(3):
                time.sleep(0.4)
                print(".", end="", flush=True)

            print()

            poem = get_poetic_response(user_input, chat_history)

            display_response(poem)

            chat_history.append({"role": "user", "content": user_input})
            chat_history.append({"role": "model", "content": poem})

            if len(chat_history) > MAX_HISTORY_TURNS * 2:
                chat_history = chat_history[-(MAX_HISTORY_TURNS * 2):]

            print()

        except KeyboardInterrupt:

            print("\nSession ended.")
            break


run_chatbot()

# Testing chatbot with sample inputs

demo_messages = [
    "My name is Diya.",
    "I study in BITS Pilani, Goa.",
    "I am a mechanical student.",
    "Sade is my favorite artist.",
]

demo_history = []

for message in demo_messages:

    print(f"User: {message}")

    print("  Generating response", end="", flush=True)

    for _ in range(3):
        time.sleep(0.3)
        print(".", end="", flush=True)

    print()

    poem = get_poetic_response(message, demo_history)

    display_response(poem)

    demo_history.append({"role": "user", "content": message})
    demo_history.append({"role": "model", "content": poem})

print("Demo complete!")

